### ISSUE TITLE
Sensitive data

### ISSUE THREAD

**Issue by diego-a-pf** [csap-platform/csap-build#1]
I contact you on behalf of your former company, could you please remove all sensitive information included in this repository, links, usernames and passwords.
Kind regards

**Comment by peterdnight** [comment]
Example?

**Comment by diego-a-pf** [comment]
on file: https://github.com/csap-platform/csap-build/blob/master/resources/csap-settings.xml
from line 10 to 60

**Comment by peterdnight** [comment]
I am current out of town - and temp masked the change. When back - I will
delete the reference.

**Comment by diego-a-pf** [comment]
Thanks!
