### ISSUE TITLE
[URGENT] Sensitive data removal request.

### ISSUE THREAD

**Issue by delt0** [csap-platform/csap-build#2]
Hello there, It has come to our attention that several repositories posted here are containing sensitive data from our client's infrastructure.

Please delete these repositories or make them private, here is the full list:

https://github.com/csap-platform/csap-build/commit/936e1ec86049a8ded7d1f70d41fb6cd7bacc4850
https://github.com/csap-platform/csap-bin/blob/master/csap-package-linux-secondary/deploy_govc.sh
https://github.com/csap-platform/csap-bin/commit/ef05c4a3254568f91ffdf31502c52dfdd75dab42
csap-bin/csap-package-httpd-uber/externalDeploy.sh
csap-bin/csap-package-java-secondary/externalDeploy.sh
csap-bin/csap-package-linux-secondary/deploy_govc.sh
csap-bin/csap-package-linux-secondary/deploy_helm.sh
csap-bin/csap-package-linux-secondary/deploy_maven.sh
csap-bin/csap-package-monitoring-secondary/externalDeploy.shcsap-bin/pom.xml
Breadcrumbscsap-build/vars/template.groovy
csap-images/csap-test-app/docker/Dockerfile
csap-images/csap-test-app/docker/Dockerfile
csap-images/mongo/resources/eventSamples.js
csap-images/pom.xml
csap-installer/eol/registry_deploy/pom.xml
csap-installer/eol/pom.xml
csap-installer/pom.xml
csap-core/csap-core-service/devData/stubResults/admin/csap-reference-status.json
csap-core/csap-core-service/devData/stubResults/admin/host-status-scorecard-test.json
csap-core/csap-core-service/devData/stubResults/agent/runtime-host-k8.json
Breadcrumbscsap-core/csap-core-service/devData/stubResults/crio/crictl-inspect-calico.json
csap-core/csap-core-service/devData/stubResults/govc/datastore-all.txt
csap-core/csap-core-service/devData/stubResults/govc/list-root.json
csap-core/csap-core-service/devData/stubResults/govc/vm-console-launch
csap-core/csap-core-service/devData/stubResults/govc/vm-device-info.json
csap-core/csap-core-service/devData/stubResults/govc/vm-find.txt
csap-core/csap-core-service/devData/stubResults/govc/vm-info.json
csap-core-service/devData/stubResults/govc/vm-list.txt
csap-core-service/devData/stubResults/helm/show-readme.txt
csap-core-service/devData/stubResults/helm/show-values.txt
csap-core-service/devData/stubResults/httpCollect/csap-reference-app.json
csap-core-service/devData/stubResults/httpCollect/csap-reference-health.json
csap-core-service/devData/stubResults/httpCollect/csap-reference-java.json
csap-core/csap-core-service/devData/stubResults/linux/buildResults.txt
csap-core-service/devData/stubResults/linux/docker-system-df.txt
csap-core-service/devData/stubResults/linux/iptables-kube-services.txt
csap-core-service/devData/stubResults/linux/kubeadm-join.txt
csap-core-service/devData/stubResults/linux/kubernetes-describe-nodes.txt
csap-core-service/devData/stubResults/linux/network-ports-connections.txt
csap-core-service/devData/stubResults/linux/network-ports-listen.txt
csap-core-service/devData/stubResults/linux/pod-describe.txt
csap-core-service/devData/stubResults/linux/ps-socket-stat.txt
csap-core-service/devData/stubResults/linux/psMemory.txt
csap-core-service/devData/stubResults/linux/sample-script-output.txt
csap-core-service/devData/stubResults/linux/searchResults.txt
csap-core-service/devData/stubResults/linux/socketStat.txt
csap-core-service/devData/stubResults/linux/systemctl-status.txt

Please let me know if you need anything from my side in order to proceed with this request.

Thanks & regards.

**Comment by peterdnight** [comment]
i have switched repos to private.

**Comment by delt0** [comment]
Many thanks sir, very appreciated.
